### PR TITLE
Add feed for Table Titans (tabletitans.com)

### PR DESCRIPTION
**Pull request by iqbalansari**

### CODE REVIEW

**Comment by cbenard** [comment]
I pulled your change into a temp branch locally and I couldn't get it to work. You have a bug in the TableTitansService. Your constructor uses "pvp" instead of a new "tabletitans". I'm fixing that. Also, in dependency_injection.php you added an extra newline at the end I'm removing (I'd just like to keep it the same; I don't mind additions).

**Comment by cbenard** [comment]
Active now @ http://comicfeeds.chrisbenard.net/view/tabletitans/default

**Comment by iqbalansari** [comment]
Apologies for the errors, I tested it lightly on my local and it seemed to work. I will be more careful about whitespace changes in future.

Thanks

**Comment by cbenard** [comment]
No problem. I appreciate the additions for the comics you like. I'm not sure how Table Titans could have worked, though. Your TableTitansService was storing them in "pvp" (I'm guessing you used your pvp service as a template), not in "tabletitans". See my latest commit a2e9778 for the changes I made.

**Comment by iqbalansari** [comment]
> I'm guessing you used your pvp service as a template

Exactly I simply copied the pvp service and made the changes required for Table Titans, somehow I missed the constructor :disappointed:

**Pull request merged**
